# Generated by Django 5.2.8 on 2026-05-17 12:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=255, unique=True)),
                ('hindi_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(help_text='Example: 2020NITSGR033', max_length=100, unique=True)),
                ('enrollment_no', models.CharField(help_text='Example: ITE/22/16', max_length=100)),
                ('english_name', models.CharField(help_text='Example: Sonia Yadav', max_length=255)),
                ('hindi_name', models.CharField(help_text='Example: सोनिया यादव', max_length=255)),
                ('degree', models.CharField(choices=[('BTECH', 'Bachelor of Technology'), ('MTECH', 'Master of Technology'), ('PHD', 'Doctor of Philosophy')], default='BTECH', max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('completion_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='July', max_length=20)),
                ('completion_year', models.PositiveIntegerField()),
                ('award_date', models.DateField()),
                ('student_photo', models.ImageField(upload_to='students/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.department')),
            ],
        ),
    ]
