# Generated by Django 5.2.8 on 2026-05-17 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-completion_year'], 'verbose_name': 'Student Certificate', 'verbose_name_plural': 'Student Certificates'},
        ),
        migrations.AlterField(
            model_name='student',
            name='completion_year',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(help_text='Example: ITE/22/16', max_length=100, validators=[django.core.validators.RegexValidator(message='Example: ITE/22/16', regex='^[A-Z]+\\/[0-9]+\\/[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(db_index=True, help_text='Example: 2020NITSGR033', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Example: 2020NITSGR033', regex='^[0-9]{4}NITSGR[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(upload_to='students/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
